package com.relly.blog.mapper;

import com.relly.blog.entity.ArticleStarEntity;
import org.apache.ibatis.annotations.Param;

public interface ArticleStarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_star
     *
     * @mbg.generated
     */
    int insert(ArticleStarEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_star
     *
     * @mbg.generated
     */
    int insertSelective(ArticleStarEntity record);

    int getStarNumByArticleId(@Param("articleId") String articleId);

    int getStarNumByArticleIdAndUserId(@Param("articleId")String articleId, @Param("userId")String userId);

    void delRecord(@Param("articleId") String articleId,@Param("userId") String userId);
}