package com.relly.blog.mapper;

import com.relly.blog.entity.ArticleStarEntity;

public interface ArticleStarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_star
     *
     * @mbg.generated
     */
    int insert(ArticleStarEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_star
     *
     * @mbg.generated
     */
    int insertSelective(ArticleStarEntity record);
}