package com.relly.blog.mapper;

import com.relly.blog.common.model.PageObject;
import com.relly.blog.common.model.PageResult;
import com.relly.blog.dto.ArticleDTO;
import com.relly.blog.dto.ArticleFilterDTO;
import com.relly.blog.dto.ArticleMessageDTO;
import com.relly.blog.entity.ArticleEntity;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    int insert(ArticleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    int insertSelective(ArticleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    ArticleEntity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ArticleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ArticleEntity record);

    List<ArticleDTO> getArticleListByUser(@Param("userId") String userId);

    int gettMyArticleListCount(@Param("userId") String userId);

    List<ArticleDTO> getMyArticleListMore(@Param("userId") String userId, @Param("pageObject")PageObject pageObject);

    ArticleDTO getArticleDetail(@Param(("articleId")) String articleId);

    List<ArticleMessageDTO> getArticleMessage(@Param("articleId") String articleId,@Param("pageObject") PageObject pageObject);

    List<ArticleMessageDTO> getArticleMessage1(@Param("articleId") String articleId,@Param("pageObject") PageObject pageObject);

    List<ArticleMessageDTO> getArticleMessageChildren(@Param("parentId") String parentId,@Param("articleId") String articleId);

    int getArticleMessageCount(@Param("articleId") String articleId);

    int getAllArticleListCount();

    List<ArticleDTO> getAllArticleList(@Param("articleFilterDTO")ArticleFilterDTO articleFilterDTO,
                                       @Param("typeList")List<String> typeList,
                                       @Param("pageObject")PageObject pageObject);
}