package com.relly.blog.mapper;

import com.relly.blog.entity.CityEntity;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbg.generated
     */
    int insert(CityEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbg.generated
     */
    int insertSelective(CityEntity record);

    List<CityEntity> getCityListByPId(@Param("pId") String pId);
}