package com.relly.blog.mapper;

import com.relly.blog.common.model.PageObject;
import com.relly.blog.dto.PermissionDTO;
import com.relly.blog.entity.PermissionEntity;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated
     */
    int insert(PermissionEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated
     */
    int insertSelective(PermissionEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated
     */
    PermissionEntity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PermissionEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PermissionEntity record);

    int getCountByNameAndPermission(@Param("name") String name,@Param("permission") String permission);

    int getListCount();

    List<PermissionEntity> getPermissionList(@Param("pageObject")PageObject pageObject);

    List<PermissionEntity> pmenuList(@Param("type") String type);

    List<PermissionDTO> getAllPmenuList();

    List<PermissionDTO> getSmenuList(@Param("id") String id, @Param("idList")List pidList);

    List<String> getPidbyUid(@Param("userId")String userId);

    List<PermissionDTO> getPmenuList(@Param("userId")String userId);
}