package com.relly.blog.mapper;

import com.relly.blog.entity.ProvinceEntity;

import java.util.List;

public interface ProvinceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbg.generated
     */
    int insert(ProvinceEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbg.generated
     */
    int insertSelective(ProvinceEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbg.generated
     */
    ProvinceEntity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProvinceEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProvinceEntity record);

    List<ProvinceEntity> getAllProvinceList();
}