package com.relly.blog.mapper;

import com.relly.blog.common.model.PageObject;
import com.relly.blog.dto.RoleDto;
import com.relly.blog.entity.RoleEntity;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated
     */
    int insert(RoleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated
     */
    int insertSelective(RoleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated
     */
    RoleEntity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RoleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RoleEntity record);

    List<RoleEntity> getRoleListByUserId(@Param("userId") String userId);

    int getRoleListCount();

    List<RoleDto> getRoleList(@Param("pageObject") PageObject pageObject);

    int getCountByName(@Param("role") String role);

    void insertBatch(@Param("uids") List<String> uids, @Param("roleId") String roleId);

    void delBatch(@Param("uids") List<String> uids, @Param("roleId") String roleId);

    List<String> getPermissionByRole(@Param("roleId") String roleId);

    void insertBatchPermission(@Param("targetPermissions") List<String> targetPermissions, @Param("roleId") String roleId);

    void delBatchPermission(@Param("targetPermissions") List<String> targetPermissions, @Param("roleId") String roleId);
}