package com.relly.blog.mapper;

import com.relly.blog.dto.UserDetailDTO;
import com.relly.blog.entity.UserDetailEntity;

public interface UserDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail
     *
     * @mbg.generated
     */
    int insert(UserDetailEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail
     *
     * @mbg.generated
     */
    int insertSelective(UserDetailEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail
     *
     * @mbg.generated
     */
    UserDetailEntity selectByPrimaryKey(String id);

    UserDetailEntity selectByUserId(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserDetailEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserDetailEntity record);


    UserDetailEntity getUserDetailByUserId(String userId);

    int countUserDetailByUserId(String userId);

    UserDetailDTO getUserDetailDTOByUserId(String userId);
}