package com.relly.blog.entity;

import java.io.Serializable;

public class ArticleMessageEntity extends CommonBaseEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_message.articleId
     *
     * @mbg.generated
     */
    private String articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_message.userId
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_message.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_message.aite
     *
     * @mbg.generated
     */
    private String aite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table article_message
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_message.articleId
     *
     * @return the value of article_message.articleId
     *
     * @mbg.generated
     */
    public String getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_message.articleId
     *
     * @param articleId the value for article_message.articleId
     *
     * @mbg.generated
     */
    public void setArticleId(String articleId) {
        this.articleId = articleId == null ? null : articleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_message.userId
     *
     * @return the value of article_message.userId
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_message.userId
     *
     * @param userId the value for article_message.userId
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_message.content
     *
     * @return the value of article_message.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_message.content
     *
     * @param content the value for article_message.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_message.aite
     *
     * @return the value of article_message.aite
     *
     * @mbg.generated
     */
    public String getAite() {
        return aite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_message.aite
     *
     * @param aite the value for article_message.aite
     *
     * @mbg.generated
     */
    public void setAite(String aite) {
        this.aite = aite == null ? null : aite.trim();
    }
}