package com.relly.blog.entity;

import java.io.Serializable;

public class ArticleStarEntity extends CommonBaseEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_star.articleId
     *
     * @mbg.generated
     */
    private String articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_star.userId
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table article_star
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_star.articleId
     *
     * @return the value of article_star.articleId
     *
     * @mbg.generated
     */
    public String getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_star.articleId
     *
     * @param articleId the value for article_star.articleId
     *
     * @mbg.generated
     */
    public void setArticleId(String articleId) {
        this.articleId = articleId == null ? null : articleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_star.userId
     *
     * @return the value of article_star.userId
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_star.userId
     *
     * @param userId the value for article_star.userId
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }
}