package com.relly.blog.entity;

import lombok.Data;

@Data
public class WxUserEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   小程序用户openid
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.openid
     *
     * @mbg.generated
     */
    private String openid;

    /**
     * Database Column Remarks:
     *   用户昵称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.nickname
     *
     * @mbg.generated
     */
    private String nickName;

    /**
     * Database Column Remarks:
     *   用户头像
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.avatarUrl
     *
     * @mbg.generated
     */
    private String avatarUrl;

    /**
     * Database Column Remarks:
     *   性别   0 男  1  女  2 人妖
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.gender
     *
     * @mbg.generated
     */
    private Boolean gender;

    /**
     * Database Column Remarks:
     *   所在国家
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.country
     *
     * @mbg.generated
     */
    private String country;

    /**
     * Database Column Remarks:
     *   省份
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.province
     *
     * @mbg.generated
     */
    private String province;

    /**
     * Database Column Remarks:
     *   城市
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.language
     *
     * @mbg.generated
     */
    private String language;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.ctime
     *
     * @mbg.generated
     */
    private Integer ctime;

    /**
     * Database Column Remarks:
     *   手机类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.mobile
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     * Database Column Remarks:
     *   手机号码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.telnum
     *
     * @mbg.generated
     */
    private String telnum;

    private String loginUserId;


}